### ISSUE TITLE
Write an LDAP scraper to update User nodes

### ISSUE THREAD

**Issue by mprahl** [release-engineering/estuary-api#22]
Right now, our User nodes are built from data from services that those users use, but we should update those User nodes with canonical information from LDAP such as their actual name.

This is not urgent but it is nice to have.

**Comment by ralphbean** [comment]
Is this a rainy day issue?  :P  I assume we don't have a real use case for it yet.

FWIW, it might be worthwhile to just close it for now and recreate it when we have a real use case pop up.  Up to you!
