### ISSUE TITLE
Re-factor monitor module

### ISSUE THREAD

**Issue by fivaldi** [release-engineering/estuary-api#224]
Re-factor the monitor module from https://pagure.io/monitor-flask-sqlalchemy on occasion when new metrics are added/changed or on other changes to the current module. See #223 for background.

**Comment by mprahl** [comment]
Since the monitoring module is for Flask-SQLAlchemy, and we don't use SQLAlchemy, I'm going to close this. There's currently very little code for this in Estuary any how. So I'm going to close this.
